server:
  port: 9000
  servlet:
    context-path: /craftbeer
    
spring:
  datasource:
    url: jdbc:h2:mem:craftbeerdb
    username: root
    password: 
    
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
      