server:
  port: 9000
  servlet:
    context-path: /craftbeer
    
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/craftbeerdb
    username: root
    password: 
    
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
      